In [114]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
# Set up visual style
sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

In [115]:
# Load the dataset

import pandas as pd

# If you uploaded a zip file, unzip first
import zipfile

with zipfile.ZipFile("/content/Zomato Dataset.csv (1).zip", 'r') as zip_ref:
    zip_ref.extractall("/content")

In [116]:


# Now load CSV properly
df = pd.read_csv("/content/Zomato Dataset.csv",
                 delimiter=",",    # change to ";" or "\t" if needed
                 encoding="utf-8", # try "latin1" if utf-8 gives errors
                 low_memory=False)

print(df.shape)
print(df.columns)
df.head()

(45584, 20)
Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weather_conditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken (min)'],
      dtype='object')

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

# Data cleaning and preprocessing ---------

In [117]:
df_copy=df.copy()

In [118]:
df_copy.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [119]:
# Check number of duplicate rows
num_duplicates = df_copy.duplicated().sum()

print(f"🔍 Number of duplicate rows in dataset: {num_duplicates}")

🔍 Number of duplicate rows in dataset: 0

In [120]:

print("Shape of dataset:", df.shape)

Shape of dataset: (45584, 20)

In [121]:
print("\nData Types:\n", df.dtypes)

Data Types:
 ID                              object
Delivery_person_ID              object
Delivery_person_Age            float64
Delivery_person_Ratings        float64
Restaurant_latitude            float64
Restaurant_longitude           float64
Delivery_location_latitude     float64
Delivery_location_longitude    float64
Order_Date                      object
Time_Orderd                     object
Time_Order_picked               object
Weather_conditions              object
Road_traffic_density            object
Vehicle_condition                int64
Type_of_order                   object
Type_of_vehicle                 object
multiple_deliveries            float64
Festival                        object
City                            object
Time_taken (min)                 int64
dtype: object

In [122]:
# Standardize column names
# ---------------------------
df.columns = [col.strip().replace(" ", "_").replace("(", "").replace(")", "").lower()
              for col in df.columns]
df.tail()

,id,delivery_person_id,delivery_person_age,delivery_person_ratings,restaurant_latitude,restaurant_longitude,delivery_location_latitude,delivery_location_longitude,order_date,time_orderd,time_order_picked,weather_conditions,road_traffic_density,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city,time_taken_min
45579,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35,11:45,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32
45580,0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55,20:10,Windy,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36
45581,0x4f8d,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50,24:05:00,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
45582,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35,13:40,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
45583,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10,17:15,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

In [123]:
# Convert order_date
df['order_date'] = pd.to_datetime(df['order_date'], format='%d-%m-%Y', errors='coerce')

In [124]:
# Convert time columns (hour:minute format)
df['time_orderd'] = pd.to_datetime(df['time_orderd'], format='%H:%M', errors='coerce')
df['time_order_picked'] = pd.to_datetime(df['time_order_picked'], format='%H:%M', errors='coerce')

In [125]:
# Drop rows with invalid times
df.dropna(subset=['time_orderd', 'time_order_picked'], inplace=True)

In [126]:
# Critical columns that must not be null
critical_cols = ['order_date', 'time_orderd', 'time_order_picked',
                 'weather_conditions', 'city', 'time_taken_min']
df.dropna(subset=critical_cols, inplace=True)

In [127]:
# drop duplicates

df.drop_duplicates(inplace=True)

In [128]:
df.drop(columns=["vehicle_condition"])

,id,delivery_person_id,delivery_person_age,delivery_person_ratings,restaurant_latitude,restaurant_longitude,delivery_location_latitude,delivery_location_longitude,order_date,time_orderd,time_order_picked,weather_conditions,road_traffic_density,type_of_order,type_of_vehicle,multiple_deliveries,festival,city,time_taken_min
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,2022-02-12,1900-01-01 21:55:00,1900-01-01 22:10:00,Fog,Jam,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,2022-02-13,1900-01-01 14:55:00,1900-01-01 15:05:00,Stormy,High,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,2022-03-04,1900-01-01 17:30:00,1900-01-01 17:40:00,Sandstorms,Medium,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,2022-02-13,1900-01-01 09:20:00,1900-01-01 09:30:00,Sandstorms,Low,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,2022-02-14,1900-01-01 19:50:00,1900-01-01 20:05:00,Fog,Jam,Snack,scooter,1.0,No,Metropolitian,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45578,0x1178,RANCHIRES16DEL01,35.0,4.2,23.371292,85.327872,23.481292,85.437872,2022-03-08,1900-01-01 21:45:00,1900-01-01 21:55:00,Windy,Jam,Drinks,motorcycle,1.0,No,Metropolitian,33
45579,0x7c09,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,2022-03-24,1900-01-01 11:35:00,1900-01-01 11:45:00,Windy,High,Meal,motorcycle,0.0,No,Metropolitian,32
45580,0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,2022-02-16,1900-01-01 19:55:00,1900-01-01 20:10:00,Windy,Jam,Buffet,motorcycle,1.0,No,Metropolitian,36
45582,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,2022-03-07,1900-01-01 13:35:00,1900-01-01 13:40:00,Cloudy,High,Snack,motorcycle,1.0,No,Metropolitian,26
45583,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,2022-03-02,1900-01-01 17:10:00,1900-01-01 17:15:00,Fog,Medium,Snack,scooter,1.0,No,Metropolitian,36

In [129]:
df.head()

,id,delivery_person_id,delivery_person_age,delivery_person_ratings,restaurant_latitude,restaurant_longitude,delivery_location_latitude,delivery_location_longitude,order_date,time_orderd,time_order_picked,weather_conditions,road_traffic_density,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city,time_taken_min
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,2022-02-12,1900-01-01 21:55:00,1900-01-01 22:10:00,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,2022-02-13,1900-01-01 14:55:00,1900-01-01 15:05:00,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,2022-03-04,1900-01-01 17:30:00,1900-01-01 17:40:00,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,2022-02-13,1900-01-01 09:20:00,1900-01-01 09:30:00,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,2022-02-14,1900-01-01 19:50:00,1900-01-01 20:05:00,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

# Basic EDA --------

**Basic Info**

In [130]:
print("Shape of dataset:", df.shape)

Shape of dataset: (34487, 20)

In [131]:
# Summary Stats
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34487 entries, 0 to 45583
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           34487 non-null  object
 1   delivery_person_id           34487 non-null  object
 2   delivery_person_age          34319 non-null  float64
 3   delivery_person_ratings      34280 non-null  float64
 4   restaurant_latitude          34487 non-null  float64
 5   restaurant_longitude         34487 non-null  float64
 6   delivery_location_latitude   34487 non-null  float64
 7   delivery_location_longitude  34487 non-null  float64
 8   order_date                   34487 non-null  datetime64[ns]
 9   time_orderd                  34487 non-null  datetime64[ns]
 10  time_order_picked            34487 non-null  datetime64[ns]
 11  weather_conditions           34487 non-null  object
 12  road_traffic_density         34487 non-null  object
 13  vehicle_condition            34487 non-null  int64
 14  type_of_order                34487 non-null  object
 15  type_of_vehicle              34487 non-null  object
 16  multiple_deliveries          33752 non-null  float64
 17  festival                     34328 non-null  object
 18  city                         34487 non-null  object
 19  time_taken_min               34487 non-null  int64
dtypes: datetime64[ns](3), float64(7), int64(2), object(8)
memory usage: 5.5+ MB

In [132]:
print("\nDescriptive Statistics:")
print(df.describe(include='all'))

Descriptive Statistics:
            id delivery_person_id  delivery_person_age  \
count    34487              34487         34319.000000
unique   34487               1320                  NaN
top     0x5fb2      SURRES11DEL01                  NaN
freq         1                 56                  NaN
mean       NaN                NaN            29.604447
min        NaN                NaN            20.000000
25%        NaN                NaN            25.000000
50%        NaN                NaN            30.000000
75%        NaN                NaN            35.000000
max        NaN                NaN            39.000000
std        NaN                NaN             5.768777

        delivery_person_ratings  restaurant_latitude  restaurant_longitude  \
count              34280.000000         34487.000000          34487.000000
unique                      NaN                  NaN                   NaN
top                         NaN                  NaN                   NaN
freq                        NaN                  NaN                   NaN
mean                   4.634460            17.241695             70.799226
min                    2.500000           -30.902872              0.000000
25%                    4.500000            12.933298             73.170937
50%                    4.700000            18.551440             75.898497
75%                    4.900000            22.732225             78.045732
max                    5.000000            30.914057             88.433452
std                    0.314288             7.696580             21.074927

        delivery_location_latitude  delivery_location_longitude  \
count                 34487.000000                 34487.000000
unique                         NaN                          NaN
top                            NaN                          NaN
freq                           NaN                          NaN
mean                     17.464015                    70.862839
min                       0.010000                     0.010000
25%                      12.985996                    73.288921
50%                      18.632450                    76.004377
75%                      22.784648                    78.107115
max                      31.045562                    88.563452
std                       7.332142                    21.075231

                           order_date                    time_orderd  \
count                           34487                          34487
unique                            NaN                            NaN
top                               NaN                            NaN
freq                              NaN                            NaN
mean    2022-03-13 16:23:09.601878784  1900-01-01 18:01:27.772204288
min               2022-02-11 00:00:00            1900-01-01 08:10:00
25%               2022-03-04 00:00:00            1900-01-01 15:45:00
50%               2022-03-15 00:00:00            1900-01-01 19:15:00
75%               2022-03-27 00:00:00            1900-01-01 21:30:00
max               2022-04-06 00:00:00            1900-01-01 23:50:00
std                               NaN                            NaN

                    time_order_picked weather_conditions road_traffic_density  \
count                           34487              34487                34487
unique                            NaN                  6                    4
top                               NaN                Fog                  Low
freq                              NaN               5853                11474
mean    1900-01-01 18:11:24.397018880                NaN                  NaN
min               1900-01-01 08:15:00                NaN                  NaN
25%               1900-01-01 15:55:00                NaN                  NaN
50%               1900-01-01 19:25:00                NaN                  NaN
75%               1900-01-01 21:40:00                NaN                  NaN
max               1900-01-01 23:55:00                NaN                  NaN
std                               NaN                NaN                  NaN

        vehicle_condition type_of_order type_of_vehicle  multiple_deliveries  \
count        34487.000000         34487           34487         33752.000000
unique                NaN             4               3                  NaN
top                   NaN         Snack      motorcycle                  NaN
freq                  NaN          8696           20260                  NaN
mean             0.997651           NaN             NaN             0.747037
min              0.000000           NaN             NaN             0.000000
25%              0.000000           NaN             NaN             0.000000
50%              1.000000           NaN             NaN             1.000000
75%              2.000000           NaN             NaN             1.000000
max              2.000000           NaN             NaN             3.000000
std              0.817316           NaN             NaN             0.574260

       festival           city  time_taken_min
count     34328          34487    34487.000000
unique        2              3             NaN
top          No  Metropolitian             NaN
freq      33641          26476             NaN
mean        NaN            NaN       26.454461
min         NaN            NaN       10.000000
25%         NaN            NaN       19.000000
50%         NaN            NaN       26.000000
75%         NaN            NaN       33.000000
max         NaN            NaN       54.000000
std         NaN            NaN        9.393571

In [133]:
# for numerical attributes (summary of numeric columns (count, mean, std, quartiles, min, max))
df.describe(include=np.number).T

,count,mean,std,min,25%,50%,75%,max
delivery_person_age,34319.0,29.604447,5.768777,20.000000,25.000000,30.000000,35.000000,39.000000
delivery_person_ratings,34280.0,4.634460,0.314288,2.500000,4.500000,4.700000,4.900000,5.000000
restaurant_latitude,34487.0,17.241695,7.696580,-30.902872,12.933298,18.551440,22.732225,30.914057
restaurant_longitude,34487.0,70.799226,21.074927,0.000000,73.170937,75.898497,78.045732,88.433452
delivery_location_latitude,34487.0,17.464015,7.332142,0.010000,12.985996,18.632450,22.784648,31.045562
delivery_location_longitude,34487.0,70.862839,21.075231,0.010000,73.288921,76.004377,78.107115,88.563452
vehicle_condition,34487.0,0.997651,0.817316,0.000000,0.000000,1.000000,2.000000,2.000000
multiple_deliveries,33752.0,0.747037,0.574260,0.000000,0.000000,1.000000,1.000000,3.000000
time_taken_min,34487.0,26.454461,9.393571,10.000000,19.000000,26.000000,33.000000,54.000000

In [134]:
# for categorical attributes (summary of categorical columns (count, unique, top, freq))
df.describe(include="object").T

                      count unique            top   freq
id                    34487  34487         0x5fb2      1
delivery_person_id    34487   1320  SURRES11DEL01     56
weather_conditions    34487      6            Fog   5853
road_traffic_density  34487      4            Low  11474
type_of_order         34487      4          Snack   8696
type_of_vehicle       34487      3     motorcycle  20260
festival              34328      2             No  33641
city                  34487      3  Metropolitian  26476

handling missing values---------------------------

In [135]:
print("\nColumn-wise missing values:\n", df.isnull().sum())

Column-wise missing values:
 id                               0
delivery_person_id               0
delivery_person_age            168
delivery_person_ratings        207
restaurant_latitude              0
restaurant_longitude             0
delivery_location_latitude       0
delivery_location_longitude      0
order_date                       0
time_orderd                      0
time_order_picked                0
weather_conditions               0
road_traffic_density             0
vehicle_condition                0
type_of_order                    0
type_of_vehicle                  0
multiple_deliveries            735
festival                       159
city                             0
time_taken_min                   0
dtype: int64

In [136]:
# Critical columns (cannot be null)
df = df.dropna(subset=['time_orderd'])
df = df.dropna(subset=['city', 'weather_conditions'])

In [137]:
# Categorical columns (fill with mode)
df['road_traffic_density']=df['road_traffic_density'].fillna(df['road_traffic_density'].mode()[0])
df['festival']=df['festival'].fillna("No")

In [138]:
# Numeric fills
df['delivery_person_age'] = df['delivery_person_age'].fillna(df['delivery_person_age'].median())
df['delivery_person_ratings'] = df['delivery_person_ratings'].fillna(df['delivery_person_ratings'].median())
df['multiple_deliveries'] = df['multiple_deliveries'].fillna(0).astype(int)

# Verify again
print(df[['delivery_person_age','delivery_person_ratings','multiple_deliveries','festival']].isnull().sum())

delivery_person_age        0
delivery_person_ratings    0
multiple_deliveries        0
festival                   0
dtype: int64

In [139]:
df.shape

(34487, 20)

In [140]:
df.nunique()

id                             34487
delivery_person_id              1320
delivery_person_age               20
delivery_person_ratings           26
restaurant_latitude              475
restaurant_longitude             389
delivery_location_latitude      4321
delivery_location_longitude     4321
order_date                        44
time_orderd                      159
time_order_picked                174
weather_conditions                 6
road_traffic_density               4
vehicle_condition                  3
type_of_order                      4
type_of_vehicle                    3
multiple_deliveries                4
festival                           2
city                               3
time_taken_min                    45
dtype: int64

In [141]:
# handling noise(check for outliers)
print(df[['delivery_person_age','delivery_person_ratings','multiple_deliveries','time_taken_min']].describe(include=np.number).T)

                           count       mean       std   min   25%   50%   75%  \
delivery_person_age      34487.0  29.606373  5.754774  20.0  25.0  30.0  35.0
delivery_person_ratings  34487.0   4.634854  0.313385   2.5   4.5   4.7   4.9
multiple_deliveries      34487.0   0.731116  0.578261   0.0   0.0   1.0   1.0
time_taken_min           34487.0  26.454461  9.393571  10.0  19.0  26.0  33.0

                          max
delivery_person_age      39.0
delivery_person_ratings   5.0
multiple_deliveries       3.0
time_taken_min           54.0

In [142]:
for col in ['weather_conditions','road_traffic_density','festival','city']:
    df[col] = df[col].str.strip().str.lower()
    print(f"{col}: {df[col].unique()}")
# Fix typo in city
df['city'] = df['city'].replace({'metropolitian': 'metropolitan'})

weather_conditions: ['fog' 'stormy' 'sandstorms' 'windy' 'cloudy' 'sunny']
road_traffic_density: ['jam' 'high' 'medium' 'low']
festival: ['no' 'yes']
city: ['metropolitian' 'urban' 'semi-urban']

In [143]:
# Drop only if column exists
cols_to_drop = [
    'delivery_person_id',
    'vehicle_condition',
    'restaurant_latitude',
    'restaurant_longitude',
    'delivery_location_latitude',
    'delivery_location_longitude'
]

df = df.drop(columns=[col for col in cols_to_drop if col in df.columns])
print("Final dataset shape:", df.shape)
print("\nFinal Columns:")
for col in df.columns:
    print("-", col)

Final dataset shape: (34487, 14)

Final Columns:
- id
- delivery_person_age
- delivery_person_ratings
- order_date
- time_orderd
- time_order_picked
- weather_conditions
- road_traffic_density
- type_of_order
- type_of_vehicle
- multiple_deliveries
- festival
- city
- time_taken_min

In [145]:
# Export cleaned dataset
df.to_csv("Zomato_Cleaned.csv", index=False)
print("\n Clean dataset exported as 'Zomato_Cleaned.csv'")

 Clean dataset exported as 'Zomato_Cleaned.csv'